mode: train
seed: 0
interm_sup: False  # not-use.


solver:
  start_iter: 0
  early_stop: 20
  max_iters: 10000000
  max_epochs: 1000000
  batch_train: 8
  batch_val: 1
  checkpoints_period: 2000  # save model weights every checkpoints_period iterations.

mp:
  device: None
  num_gpus: 1

#output_dir: /mnt/hdd/datasets/ulsan3-crack-poc/6_tmp/4_results/1st_test
output_dir: /Users/sunn/Documents/data/dis/04_results/1st_test
